routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
   })->name("register");

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('kriteria', 'KriteriaController');
Route::resource('kandidat', 'KandidatController');
Route::get('/nilai', 'NilaiController@index')->name('nilai');
Route::get('/niai/{id}', 'NilaiController@create')->name('nilai.tambah');
Route::post('/nilai/{id}', 'NilaiController@store')->name('nilai.simpan');
Route::get('/nilai/edit/{id}', 'NilaiController@edit')->name('nilai.edit');
Route::post('/nilai/edit/{id}', 'NilaiController@update')->name('nilai.update');
Route::get('/perhitungan/list', 'PerhitunganController@list_data');
Route::get('/perhitungan/calculate', 'PerhitunganController@calculate');
Route::get('/laporan/spkwp', 'LaporanController@karyawanterbaik');

app/Kandidat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kandidat extends Model
{
    protected $table = 'kandidats';
    protected $fillable = [
        'nama',
        'alamat',
        'jk',
        'tanggal_lahir',
        'telp',
        'foto'
    ];

    public function nilai(){
        return $this->hasMany('App\Nilai','kandidat_id','id');
    }
}

app/Http/Controllers/KandidatController.php
<?php

namespace App\Http\Controllers;

use App\Kandidat;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
class KandidatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $kandidats = Kandidat::get();
        return view('kandidat.index', compact('kandidats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kandidat.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = \Validator::make($request->all(), [
            "nama" => "required|min:3|max:30",
            "telp" => "required|digits_between:9,13",
            "jk" => "required",
            "alamat" => "required",
            "tanggal_lahir" => "required"
        ])->validate();
        $new_kandidat = new \App\Kandidat;
        $new_kandidat->nama = $request->get('nama');
        $new_kandidat->jk = $request->get('jk');
        $new_kandidat->alamat = $request->get('alamat');
        $new_kandidat->tanggal_lahir = $request->get('tanggal_lahir');
        $new_kandidat->telp = $request->get('telp');
        if($request->file('foto')){
            $file = $request->file('foto')->store('gambars', 'public');
        $new_kandidat->foto = $file;
        }
        $new_kandidat->save();
        Alert::success('BERHASIL','Data Berhasil Disimpan');
        return redirect()->Route('kandidat.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kandidat  $kandidat
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kandidat = \App\Kandidat::findOrFail($id);
        return view('kandidat.show', ['kandidat' => $kandidat]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kandidat  $kandidat
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kandidat = Kandidat::findOrFail($id);
        return view('kandidat.edit', compact('kandidat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kandidat  $kandidat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = \Validator::make($request->all(), [
            "nama" => "required|min:3|max:30",
            "telp" => "required|digits_between:9,13",
            "jk" => "required",
            "alamat" => "required",
            "tanggal_lahir" => "required"
        ])->validate();

        $ubah_kandidat = \App\Kandidat::findOrFail($id);
        $ubah_kandidat->nama = $request->get('nama');
        $ubah_kandidat->jk = $request->get('jk');
        $ubah_kandidat->alamat = $request->get('alamat');
        $ubah_kandidat->tanggal_lahir = $request->get('tanggal_lahir');
        $ubah_kandidat->telp = $request->get('telp');
        if($request->file('foto')){
            if($ubah_kandidat->foto && file_exists(storage_path('app/public/' . $ubah_kandidat->foto))){
                \Storage::delete('public/'.$ubah_kandidat->foto);
            }
            $file = $request->file('foto')->store('gambars', 'public');
            $ubah_kandidat->foto = $file;
        }
        $ubah_kandidat->save();
        Alert::success('BERHASIL','Data Berhasil di Ubah');
        return redirect()->route('kandidat.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kandidat  $kandidat
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kandidat::find($id)->delete();
        Alert::success('BERHASIL','Data Berhasi di Hapus');
        return redirect()->Route('kandidat.index');
    }
}

resources/views/kandidat/create.blade.php
@extends('layouts.global')
@section('title', 'Tambah Kandidat')

@section('content')
<section class="content-header">
    <h1>
      Tambah Kandidat
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('kandidat.index')}}">Data Kandidat</a></li>
      <li class="active">Tambah Kandidat</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <!-- form start -->
            <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"
            action="{{route('kandidat.store')}}" method="POST">
            @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="nama">Nama</label>
                  <input value="{{old('nama')}}" class="form-control {{$errors->first('nama')
                    ? "is-invalid": ""}}" placeholder="Full Name" type="text" name="nama"
                    id="nama"/>
                    <div class="invalid-feedback">
                        {{$errors->first('nama')}}
                    </div>

                </div>
                <div class="form-group">
                    <label for="jk">Jenis Kelamin</label>
                        <select name="jk" class="form-control" id="jk">
                            <option value=""></option>
                            <option value="L">Laki - Laki</option>
                            <option value="P">Perempuan</option>
                        </select>
                    <div class="invalid-feedback">
                        {{$errors->first('jk')}}
                    </div>
    
                </div>
                <div class="form-group">
                  <label for="tanggal_lahir">Tanggal Lahir</label>
                  <input value="{{old('tanggal_lahir')}}" class="form-control {{$errors->first('tanggal_lahir')
                    ? "is-invalid": ""}}" type="date" name="tanggal_lahir"
                    id="tanggal_lahir"/>
                    <div class="invalid-feedback">
                        {{$errors->first('tanggal_lahir')}}
                    </div>

                </div>
                <div class="form-group">
                <label for="alamat">Alamat</label>
                <input value="{{old('alamat')}}" class="form-control {{$errors->first('alamat')
                    ? "is-invalid": ""}}" placeholder="Alamat" type="text" name="alamat"
                    id="alamat"/>
                    <div class="invalid-feedback">
                        {{$errors->first('alamat')}}
                    </div>
  
                </div>
                <div class="form-group">
                    <label for="telp">No Telpon</label>
                    <input value="{{old('telp')}}" class="form-control {{$errors->first('telp')
                      ? "is-invalid": ""}}" placeholder="No Telpon" type="text" name="telp"
                      id="telp"/>
                      <div class="invalid-feedback">
                          {{$errors->first('telp')}}
                      </div>
  
                  </div>
                
                <div class="form-group">
                  <label for="foto">Foto</label>
                  <input value="{{old('foto')}}" class="form-control {{$errors->first('foto')
                    ? "is-invalid": ""}}" type="file" name="foto"
                    id="foto"/>
                    <div class="invalid-feedback">
                        {{$errors->first('foto')}}
                    </div>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">tambah</button>
              </div>
            </form>
          </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection

resources/views/kandidat/edit.blade.php
@extends('layouts.global')
@section('title', 'Ubah Kandidat')

@section('content')
<section class="content-header">
    <h1>
      Ubah Kandidat
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('kandidat.index')}}">Data Kandidat</a></li>
      <li class="active">Ubah Kandidat</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <!-- form start -->
            <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"
            action="{{route('kandidat.update', ['id'=>$kandidat->id])}}" method="POST">
            @csrf
            <input type="hidden" value="PUT" name="_method">
              <div class="box-body">
                <div class="form-group">
                  <label for="nama">Nama</label>
                  <input value="{{old('nama') ? old('nama') : $kandidat->nama}}" class="form-control {{$errors->first('nama')
                    ? "is-invalid": ""}}" placeholder="Full Name" type="text" name="nama"
                    id="nama"/>
                    <div class="invalid-feedback">
                        {{$errors->first('nama')}}
                    </div>

                </div>
                <div class="form-group">
                    <label for="jk">Jenis Kelamin</label>
                        <select name="jk" class="form-control" id="jk">
                            <option value=""></option>
                            <option value="L" {{$kandidat->jk === "L" ? "selected" : ""}}>Laki - Laki</option>
                            <option value="P" {{$kandidat->jk === "P" ? "selected" : ""}}>Perempuan</option>
                        </select>
                    <div class="invalid-feedback">
                        {{$errors->first('jk')}}
                    </div>
    
                </div>
                <div class="form-group">
                  <label for="tanggal_lahir">Tanggal Lahir</label>
                  <input value="{{old('tanggal_lahir') ? old('tanggal_lahir') : $kandidat->tanggal_lahir}}" class="form-control {{$errors->first('tanggal_lahir')
                    ? "is-invalid": ""}}" type="date" name="tanggal_lahir"
                    id="tanggal_lahir"/>
                    <div class="invalid-feedback">
                        {{$errors->first('tanggal_lahir')}}
                    </div>

                </div>
                <div class="form-group">
                <label for="alamat">Alamat</label>
                <input value="{{old('alamat') ? old('alamat') : $kandidat->alamat}}" class="form-control {{$errors->first('alamat')
                    ? "is-invalid": ""}}" placeholder="Alamat" type="text" name="alamat"
                    id="alamat"/>
                    <div class="invalid-feedback">
                        {{$errors->first('alamat')}}
                    </div>
  
                </div>
                <div class="form-group">
                    <label for="telp">No Telpon</label>
                    <input value="{{old('telp') ? old('telp') : $kandidat->telp}}" class="form-control {{$errors->first('telp')
                      ? "is-invalid": ""}}" placeholder="No Telpon" type="text" name="telp"
                      id="telp"/>
                      <div class="invalid-feedback">
                          {{$errors->first('telp')}}
                      </div>
  
                  </div>
                
                <div class="form-group">
                  <label for="foto">Foto</label>
                  <input value="{{old('foto')}}" class="form-control {{$errors->first('foto')
                    ? "is-invalid": ""}}" type="file" name="foto"
                    id="foto"/>
                    <div class="invalid-feedback">
                        {{$errors->first('foto')}}
                    </div>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">ubah</button>
              </div>
            </form>
          </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection

resources/views/kandidat/index.blade.php
@extends('layouts.global')
@section('title', 'Data Kandidat')

@section('content')
<section class="content-header">
    <h1>
      Data Kandidat
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data Kandidat</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box">
          <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>Jenis Kelamin</th>
                        <th>No Telphone</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($kandidats as $no=>$kandidat)
                        <tr>
                            <td>{{$no + 1}}</td>
                            <td>{{$kandidat->nama}}</td>
                            <td>{{($kandidat->jk == 'L') ? 'laki-laki' : 'perempuan'}}</td>
                            <td>{{$kandidat->telp}}</td>

                            <td>
                                <a  class="btn btn-info text-white btn-sm" href="{{route('kandidat.show',$kandidat->id)}}" data-toggle="tooltip" data-placement="bottom" title="lihat data"><span class="glyphicon glyphicon-eye-open"></span></a>
                                <a  class="btn btn-warning text-white btn-sm" href="{{route('kandidat.edit',$kandidat->id)}}" data-toggle="tooltip" data-placement="bottom" title="ubah data"><span class="glyphicon glyphicon-pencil"></span></a>
                                <form id="delete-form-{{ $kandidat->id }}" action="{{ route('kandidat.destroy',$kandidat->id) }}" style="display: none;" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                <button data-toggle="tooltip" data-placement="bottom" title="hapus data" type="button" class="btn btn-danger text-white btn-sm" onclick="if(confirm('Apakah anda yakin ingin menghapus data ini?')){
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $kandidat->id }}').submit();
                                }else {
                                    event.preventDefault();
                                        }"><span class="glyphicon glyphicon-trash"></span></button>
                                
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
          
              <a href="{{ route('kandidat.create') }}" class="margin-bottom-2 btn btn-primary btn-sm btn-rounded btn-fw"><i class="fa fa-plus"></i> Tambah Kandidat</a>
            
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection
@push('javascript')
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip()
        });
    </script>
@endpush

resources/views/kandidat/show.blade.php
@extends('layouts.global')
@section('title', 'Detail Kandidat')

@section('content')
<section class="content-header">
    <h1>
      Detail Kandidat
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('kandidat.index')}}">Data Kandidat</a></li>
      <li class="active">Detail Kandidat</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <div class="box-body box-profile">
                @if($kandidat->foto)
                    <img class="profile-user-img img-responsive"  src="{{asset('storage/'.$kandidat->foto)}}" width="150px"/>
                @else
                    <img class="profile-user-img img-responsive img-circle" src="{{asset('storage/default.png')}}" alt="User profile picture">
                @endif
                <h3 class="profile-username text-center">{{$kandidat->nama}}</h3>
  
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Jenis Kelamin</b> <a class="pull-right">{{($kandidat->jk == 'L') ? 'laki-laki' : 'perempuan'}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Tanggal Lahir</b> <a class="pull-right">{{$kandidat->tanggal_lahir}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Alamat</b> <a class="pull-right">{{$kandidat->alamat}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>No Telphone</b> <a class="pull-right">{{$kandidat->telp}}</a>
                    </li>
                </ul>
            </div>
              <!-- /.box-body -->
          
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection