routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
   })->name("register");

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('kriteria', 'KriteriaController');
Route::resource('kandidat', 'KandidatController');
Route::get('/nilai', 'NilaiController@index')->name('nilai');
Route::get('/niai/{id}', 'NilaiController@create')->name('nilai.tambah');
Route::post('/nilai/{id}', 'NilaiController@store')->name('nilai.simpan');
Route::get('/nilai/edit/{id}', 'NilaiController@edit')->name('nilai.edit');
Route::post('/nilai/edit/{id}', 'NilaiController@update')->name('nilai.update');
Route::get('/perhitungan/list', 'PerhitunganController@list_data');
Route::get('/perhitungan/calculate', 'PerhitunganController@calculate');
Route::get('/laporan/spkwp', 'LaporanController@karyawanterbaik');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','foto'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::get();
        return view ('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = \Validator::make($request->all(), [
            "name" => "required|min:3|max:30",
            "email" => "required|email|unique:users",
            "password" => "required",
            "konfirmasi_password" => "required|same:password"
        ])->validate();
        $new_user = new \App\User;
        $new_user->name = $request->get('name');
        $new_user->email = $request->get('email');
        $new_user->password = bcrypt($request->get('password'));
        if($request->file('foto')){
            $file = $request->file('foto')->store('gambars', 'public');
        $new_user->foto = $file;
        }
        $new_user->save();
        Alert::success('BERHASIL','Data Berhasil Disimpan');
        return redirect()->Route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = \Validator::make($request->all(), [
            "name" => "required|min:3|max:30",
            "email" => "required|email",
        ])->validate();

        $ubah_user = \App\User::findOrFail($id);
        $ubah_user->name = $request->get('name');
        $ubah_user->email = $request->get('email');
        if($request->input('password')) {
            $ubah_user->password= bcrypt(($request->input('password')));
        }
        if($request->file('foto')){
            if($ubah_user->foto && file_exists(storage_path('app/public/' . $ubah_user->foto))){
                \Storage::delete('public/'.$ubah_user->foto);
            }
            $file = $request->file('foto')->store('gambars', 'public');
            $ubah_user->foto = $file;
        }
        $ubah_user->save();
        Alert::success('BERHASIL','Data Berhasil di Ubah');
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id)->delete();
        Alert::success('BERHASIL','User Berhasi di Hapus');
        return redirect()->Route('user.index');
    }
}

resources/views/user/create.blade.php
@extends('layouts.global')
@section('title', 'Tambah User')

@section('content')
<section class="content-header">
    <h1>
      Tambah User
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('user.index')}}">Data User</a></li>
      <li class="active">Tambah User</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <!-- form start -->
            <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"
            action="{{route('user.store')}}" method="POST">
            @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input value="{{old('name')}}" class="form-control {{$errors->first('name')
                    ? "is-invalid": ""}}" placeholder="Full Name" type="text" name="name"
                    id="name"/>
                    <div class="invalid-feedback">
                        {{$errors->first('name')}}
                    </div>

                </div>
                <div class="form-group">
                  <label for="email">Alamat Email</label>
                  <input value="{{old('email')}}" class="form-control {{$errors->first('email')
                    ? "is-invalid": ""}}" placeholder="Email" type="email" name="email"
                    id="email"/>
                    <div class="invalid-feedback">
                        {{$errors->first('email')}}
                    </div>

                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input value="{{old('password')}}" class="form-control {{$errors->first('password')
                    ? "is-invalid": ""}}" placeholder="password" type="password" name="password"
                    id="password"/>
                    <div class="invalid-feedback">
                        {{$errors->first('password')}}
                    </div>
                </div>
                <div class="form-group">
                  <label for="konfirmasi_password">Confirm Password</label>
                  <input value="{{old('konfirmasi_password')}}" class="form-control {{$errors->first('konfirmasi_password')
                    ? "is-invalid": ""}}" placeholder="Confirm Password" type="password" name="konfirmasi_password"
                    id="konfirmasi_password"/>
                    <div class="invalid-feedback">
                        {{$errors->first('konfirmasi_password')}}
                    </div>
                </div>
                <div class="form-group">
                  <label for="foto">Foto</label>
                  <input value="{{old('foto')}}" class="form-control {{$errors->first('foto')
                    ? "is-invalid": ""}}" type="file" name="foto"
                    id="foto"/>
                    <div class="invalid-feedback">
                        {{$errors->first('foto')}}
                    </div>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">tambah</button>
              </div>
            </form>
          </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.global')
@section('title', 'Ubah User')

@section('content')
<section class="content-header">
    <h1>
      Ubah User
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('user.index')}}">Data User</a></li>
      <li class="active">Ubah User</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <!-- form start -->
            <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"
            action="{{route('user.update', ['id'=>$user->id])}}" method="POST">
            @csrf
            <input type="hidden" value="PUT" name="_method">
              <div class="box-body">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input value="{{old('name') ? old('name') : $user->name}}" class="form-control {{$errors->first('name')
                    ? "is-invalid": ""}}" placeholder="Full Name" type="text" name="name"
                    id="name"/>
                    <div class="invalid-feedback">
                        {{$errors->first('name')}}
                    </div>

                </div>
                <div class="form-group">
                  <label for="email">Alamat Email</label>
                  <input value="{{old('email') ? old('email') : $user->email}}" class="form-control {{$errors->first('email')
                    ? "is-invalid": ""}}" placeholder="Email" type="email" name="email"
                    id="email"/>
                    <div class="invalid-feedback">
                        {{$errors->first('email')}}
                    </div>

                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input value="{{old('password')}}" class="form-control {{$errors->first('password')
                    ? "is-invalid": ""}}" placeholder="password" type="password" name="password"
                    id="password"/>
                    <div class="invalid-feedback">
                        {{$errors->first('password')}}
                    </div>
                </div>
                <div class="form-group">
                  <label for="foto">Foto</label>
                  <input value="{{old('foto')}}" class="form-control {{$errors->first('foto')
                    ? "is-invalid": ""}}" type="file" name="foto"
                    id="foto"/>
                    <div class="invalid-feedback">
                        {{$errors->first('foto')}}
                    </div>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">ubah</button>
              </div>
            </form>
          </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection

resources/views/user/index.blade.php
@extends('layouts.global')
@section('title', 'Data User')

@section('content')
<section class="content-header">
    <h1>
      Data User
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data User</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box">
          <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Foto</th>
                        <th>Nama Pengguna</th>
                        <th>Tanggal Dibuat</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($users as $no=>$user)
                        <tr>
                            <td>{{$no + 1}}</td>
                            <td>
                              @if($user->foto)
                                <img src="{{asset('storage/'.$user->foto)}}" width="50px"/>
                              @else
                                <img src="{{asset('storage/default.png')}}" width="50px"/>
                              @endif
                            </td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->created_at}}</td>
                            <td>
                                <a  class="btn btn-info text-white btn-sm" href="{{route('user.show',$user->id)}}" data-toggle="tooltip" data-placement="bottom" title="lihat data"><span class="glyphicon glyphicon-eye-open"></span></a>
                                <a  class="btn btn-warning text-white btn-sm" href="{{route('user.edit',$user->id)}}" data-toggle="tooltip" data-placement="bottom" title="ubah data"><span class="glyphicon glyphicon-pencil"></span></a>
                                <form id="delete-form-{{ $user->id }}" action="{{ route('user.destroy',$user->id) }}" style="display: none;" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                <button data-toggle="tooltip" data-placement="bottom" title="hapus data" type="button" class="btn btn-danger text-white btn-sm" onclick="if(confirm('Apakah anda yakin ingin menghapus data ini?')){
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $user->id }}').submit();
                                }else {
                                    event.preventDefault();
                                        }"><span class="glyphicon glyphicon-trash"></span></button>
                                
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
          
              <a href="{{ route('user.create') }}" class="margin-bottom-2 btn btn-primary btn-sm btn-rounded btn-fw"><i class="fa fa-plus"></i> Tambah Admin</a>
            
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection
@push('javascript')
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip()
        });
    </script>
@endpush

resources/views/user/show.blade.php
@extends('layouts.global')
@section('title', 'Detail User')

@section('content')
<section class="content-header">
    <h1>
      Detail User
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('user.index')}}">Data User</a></li>
      <li class="active">Detail User</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <div class="box-body box-profile">
                @if($user->foto)
                    <img class="profile-user-img img-responsive"  src="{{asset('storage/'.$user->foto)}}" width="150px"/>
                @else
                    <img class="profile-user-img img-responsive img-circle" src="{{asset('storage/default.png')}}" alt="User profile picture">
                @endif
            <br>
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Nama Admin</b> <a class="pull-right">{{$user->name}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Email</b> <a class="pull-right">{{$user->email}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Tanggal Dibuat</b> <a class="pull-right">{{$user->created_at}}</a>
                    </li>
                </ul>
            </div>
              <!-- /.box-body -->
          
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection