routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
   })->name("register");

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('kriteria', 'KriteriaController');
Route::resource('kandidat', 'KandidatController');
Route::get('/nilai', 'NilaiController@index')->name('nilai');
Route::get('/niai/{id}', 'NilaiController@create')->name('nilai.tambah');
Route::post('/nilai/{id}', 'NilaiController@store')->name('nilai.simpan');
Route::get('/nilai/edit/{id}', 'NilaiController@edit')->name('nilai.edit');
Route::post('/nilai/edit/{id}', 'NilaiController@update')->name('nilai.update');
Route::get('/perhitungan/list', 'PerhitunganController@list_data');
Route::get('/perhitungan/calculate', 'PerhitunganController@calculate');
Route::get('/laporan/spkwp', 'LaporanController@karyawanterbaik');

app/Kriteria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kriteria extends Model
{
    const BENEFIT = 'benefit';
    const COST = 'cost';
    protected $table = 'kriterias';
    protected $fillable = [
        'nama',
        'atribut',
        'bobot',
        'keterangan'
    ];
    
    public function nilai(){
        return $this->hasMany('App\Nilai','kriteria_id','id');
    }
}

app/Http/Controllers/KriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Kriteria;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class KriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $kriterias = Kriteria::get();
        return view('kriteria.index', compact('kriterias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kriteria.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = \Validator::make($request->all(), [
            "nama" => "required|min:3|max:20",
            "bobot" => "required",
            "atribut" => "required"
        ])->validate();
        $new_kriteria = new \App\Kriteria;
        $new_kriteria->nama = $request->get('nama');
        $new_kriteria->atribut = $request->get('atribut');
        $new_kriteria->bobot = $request->get('bobot');
        $new_kriteria->keterangan = $request->get('keterangan');
        $new_kriteria->save();
        Alert::success('BERHASIL','Data Berhasil Disimpan');
        return redirect()->Route('kriteria.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kriteria = \App\Kriteria::findOrFail($id);
        return view('kriteria.show', ['kriteria' => $kriteria]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kriteria = Kriteria::find($id);
        return view('kriteria.edit', compact('kriteria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = \Validator::make($request->all(), [
            "nama" => "required|min:3|max:20",
            "bobot" => "required",
            "atribut" => "required"
        ])->validate();

        $ubah_kriteria = \App\Kriteria::find($id);
        $ubah_kriteria->nama = $request->get('nama');
        $ubah_kriteria->atribut = $request->get('atribut');
        $ubah_kriteria->bobot = $request->get('bobot');
        $ubah_kriteria->keterangan = $request->get('keterangan');
        $ubah_kriteria->save();
        Alert::success('BERHASIL','Data Berhasil Diubah');
        return redirect()->Route('kriteria.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kriteria::find($id)->delete();
        Alert::success('BERHASIL','Data Berhasi di Hapus');
        return redirect()->Route('kriteria.index');
    }
}

resources/views/kriteria/create.blade.php
@extends('layouts.global')
@section('title', 'Tambah Kriteria')

@section('content')
<section class="content-header">
    <h1>
      Tambah Kriteria
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('kriteria.index')}}">Data Kriteria</a></li>
      <li class="active">Tambah Kriteria</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <!-- form start -->
            <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"
            action="{{route('kriteria.store')}}" method="POST">
            @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="nama">Nama Kriteria</label>
                  <input value="{{old('nama')}}" class="form-control {{$errors->first('nama')
                    ? "is-invalid": ""}}" placeholder="Nama Kriteria" type="text" name="nama"
                    id="nama"/>
                    <div class="invalid-feedback">
                        {{$errors->first('nama')}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="atribut">Atribut</label>
                    <select name="atribut" class="form-control" id="atribut">
                        <option value=""></option>
                        <option value="benefit">Benefit</option>
                        <option value="cost">Cost</option>
                    </select>
                    <div class="invalid-feedback">
                        {{$errors->first('atribut')}}
                    </div>
                </div>
                <div class="form-group">
                <label for="bobot">Bobot</label>
                <input value="{{old('bobot')}}" class="form-control {{$errors->first('bobot')
                    ? "is-invalid": ""}}" placeholder="Bobot" type="text" name="bobot"
                    id="bobot"/>
                    <div class="invalid-feedback">
                        {{$errors->first('bobot')}}
                    </div>
                </div>
                <div class="form-group">
                  <label for="keterangan">Keterangan</label>
                  <input value="{{old('keterangan')}}" class="form-control {{$errors->first('keterangan')
                      ? "is-invalid": ""}}" placeholder="Keterangan" type="text" name="keterangan"
                      id="keterangan"/>
                      <div class="invalid-feedback">
                          {{$errors->first('keterangan')}}
                      </div>
                  </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">tambah</button>
              </div>
            </form>
          </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection

resources/views/kriteria/edit.blade.php
@extends('layouts.global')
@section('title', 'Ubah Kriteria')

@section('content')
<section class="content-header">
    <h1>
      Ubah Kriteria
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('kriteria.index')}}">Data Kriteria</a></li>
      <li class="active">Ubah Kriteria</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <!-- form start -->
            <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"
            action="{{route('kriteria.update', ['id'=>$kriteria->id])}}" method="POST">
            @csrf
            <input type="hidden" value="PUT" name="_method">
              <div class="box-body">
                <div class="form-group">
                  <label for="nama">Nama Kriteria</label>
                  <input value="{{old('nama') ? old('nama') : $kriteria->nama}}" class="form-control {{$errors->first('nama')
                    ? "is-invalid": ""}}" placeholder="Nama Kriteria" type="text" name="nama"
                    id="nama"/>
                    <div class="invalid-feedback">
                        {{$errors->first('nama')}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="atribut">Atribut</label>
                    <select name="atribut" class="form-control" id="atribut">
                        <option value=""></option>
                        <option value="benefit" {{$kriteria->atribut === "benefit" ? "selected" : ""}}>Benefit</option>
                        <option value="cost" {{$kriteria->atribut === "cost" ? "selected" : ""}}>Cost</option>
                    </select>
                    <div class="invalid-feedback">
                        {{$errors->first('atribut')}}
                    </div>
                </div>
                <div class="form-group">
                <label for="bobot">Bobot</label>
                <input value="{{old('bobot') ? old('bobot') : $kriteria->bobot}}" class="form-control {{$errors->first('bobot')
                    ? "is-invalid": ""}}" placeholder="Bobot" type="text" name="bobot"
                    id="bobot"/>
                    <div class="invalid-feedback">
                        {{$errors->first('bobot')}}
                    </div>
                </div>
                <div class="form-group">
                  <label for="keterangan">Keterangan</label>
                  <input value="{{old('keterangan') ? old('keterangan') : $kriteria->keterangan}}" class="form-control {{$errors->first('keterangan')
                      ? "is-invalid": ""}}" placeholder="Keterangan" type="text" name="keterangan"
                      id="keterangan"/>
                      <div class="invalid-feedback">
                          {{$errors->first('keterangan')}}
                      </div>
                  </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Ubah</button>
              </div>
            </form>
          </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection

resources/views/kriteria/index.blade.php
@extends('layouts.global')
@section('title', 'Data Kriteria')

@section('content')
<section class="content-header">
    <h1>
      Data Kriteria
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Data Kriteria</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box">
          <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>Atribut</th>
                        <th>Bobot</th>
                        <th width="200px">Keterangan</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($kriterias as $no=>$kriteria)
                        <tr>
                            <td>{{$no + 1}}</td>
                            <td>{{$kriteria->nama}}</td>
                            <td>{{$kriteria->atribut}}</td>
                            <td>{{$kriteria->bobot}}</td>
                            <td>{{$kriteria->keterangan}}</td>
                            <td>
                                <a  class="btn btn-info text-white btn-sm" href="{{route('kriteria.show',$kriteria->id)}}" data-toggle="tooltip" data-placement="bottom" title="lihat data"><span class="glyphicon glyphicon-eye-open"></span></a>
                                <a  class="btn btn-warning text-white btn-sm" href="{{route('kriteria.edit',$kriteria->id)}}" data-toggle="tooltip" data-placement="bottom" title="ubah data"><span class="glyphicon glyphicon-pencil"></span></a>
                                <form id="delete-form-{{ $kriteria->id }}" action="{{ route('kriteria.destroy',$kriteria->id) }}" style="display: none;" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                <button data-toggle="tooltip" data-placement="bottom" title="hapus data" type="button" class="btn btn-danger text-white btn-sm" onclick="if(confirm('Apakah anda yakin ingin menghapus data ini?')){
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $kriteria->id }}').submit();
                                }else {
                                    event.preventDefault();
                                        }"><span class="glyphicon glyphicon-trash"></span></button>
                                
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
          
              <a href="{{ route('kriteria.create') }}" class="margin-bottom-2 btn btn-primary btn-sm btn-rounded btn-fw"><i class="fa fa-plus"></i> Tambah Kriteria</a>
            
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection
@push('javascript')
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip()
        });
    </script>
@endpush

resources/views/kriteria/show.blade.php
@extends('layouts.global')
@section('title', 'Detail Kriteria')

@section('content')
<section class="content-header">
    <h1>
      Detail Kriteria
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="{{Route('kriteria.index')}}">Data Kriteria</a></li>
      <li class="active">Detail Kriteria</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
   
    <div class="row">
      <div class="col-md-12">
        
        <div class="box box-primary">
            <div class="box-body box-profile">
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Nama Kriteria</b> <a class="pull-right">{{$kriteria->nama}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Atribut</b> <a class="pull-right">{{$kriteria->atribut}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Bobot</b> <a class="pull-right">{{$kriteria->bobot}}</a>
                    </li>
                    <li class="list-group-item">
                      <b>Keterangan</b> <a class="pull-right">{{$kriteria->keterangan}}</a>
                  </li>
                </ul>
            </div>
              <!-- /.box-body -->
          
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@endsection